array set __opts {
    BackLog                 {20}
    BalloonHelp             {1}
    FrequencyDefault        {100.0}
    FrequencyList           {}
    InitDiagSizeX           {400}
    InitDiagSizeY           {300}
    MaxInterval             {50}
    PollInterval            {20}
    Position,.              {516x531+46+72}
    Position,.dataframe0    {632x417+570+72}
    PrefQuants              {
	Implicit T Time Time.Global Kl15SW SC.State SC.Start.No Brake.pMC DM.Gas DM.Clutch DM.Brake DM.GearNo DM.BrakePark DM.Shifting DM.Steer.Ang DM.Steer.Trq DM.FBrake DM.Steer.AngPos DM.Steer.Trq DM.Steer.Ang TGlob Time.Global PT.Engine.rotv DM.BrakePedal PT.Engine_rotv PT.Engine.Trq Steer.WhlAng Steer.WhlTrq Car.SimPhase Car.v Car.sRoad Car.vFL Car.vFR Car.vRL Car.vRR Car.ax Car.ay Car.az Car.Yaw Car.YawRate Car.Pitch Car.PitchVel Car.Roll Car.RollVel Car.SSAngle Car.CFL.q0 Car.CFR.q0 Car.CRL.q0 Car.CRR.q0 Car.CFL.tx Car.CFR.tx Car.CRL.tx Car.CRR.tx Car.CFL.ty Car.CFR.ty Car.CRL.ty Car.CRR.ty Car.CFL.tz Car.CFR.tz Car.CRL.tz Car.CRR.tz Car.CFL.rx Car.CFR.rx Car.CRL.rx Car.CRR.rx Car.CFL.ry Car.CFR.ry Car.CRL.ry Car.CRR.ry Car.CFL.rz Car.CFR.rz Car.CRL.rz Car.CRR.rz Car.SpringFL.Frc Car.SpringFR.Frc Car.SpringRL.Frc Car.SpringRR.Frc Car.SpringFL.l Car.SpringFR.l Car.SpringRL.l Car.SpringRR.l Car.StabiFL.Frc Car.StabiFR.Frc Car.StabiRL.Frc Car.StabiRR.Frc Car.StabiFL.l Car.StabiFR.l Car.StabiRL.l Car.StabiRR.l Car.DampFL.Frc Car.DampFR.Frc Car.DampRL.Frc Car.DampRR.Frc Car.DampFL.v Car.DampFR.v Car.DampRL.v Car.DampRR.v Car.FxFL Car.FxFR Car.FxRL Car.FxRR Car.FyFL Car.FyFR Car.FyRL Car.FyRR Car.FzFL Car.FzFR Car.FzRL Car.FzRR Car.LongSlipFL Car.LongSlipFR Car.LongSlipRL Car.LongSlipRR Car.SlipAngleFL Car.SlipAngleFR Car.SlipAngleRL Car.SlipAngleRR Car.ToeFL Car.ToeFR Car.ToeRL Car.ToeRR Car.TrqAlignFL Car.TrqAlignFR Car.TrqAlignRL Car.TrqAlignRR Brake.pFL_FL Brake.pFR_FL Brake.pRL_FL Brake.pRR_FL Brake.Trq_FL_tot Brake.Trq_FR_tot Brake.Trq_RL_tot Brake.Trq_RR_tot PT.WFL.rotv PT.WFR.rotv PT.WRL.rotv PT.WRR.rotv PT.WFL.Trq_Drive PT.WFR.Trq_Drive PT.WRL.Trq_Drive PT.WRR.Trq_Drive PT.WFL.Trq_B2W PT.WFR.Trq_B2W PT.WRL.Trq_B2W PT.WRR.Trq_B2W MC.SimPhase MC.v MC.sRoad MC.vFL MC.vFR MC.vRL MC.vRR MC.ax MC.ay MC.az MC.Yaw MC.YawRate MC.Pitch MC.PitchVel MC.Roll MC.RollVel MC.SSAngle MC.CFL.q0 MC.CFR.q0 MC.CRL.q0 MC.CRR.q0 MC.CFL.tx MC.CFR.tx MC.CRL.tx MC.CRR.tx MC.CFL.ty MC.CFR.ty MC.CRL.ty MC.CRR.ty MC.CFL.tz MC.CFR.tz MC.CRL.tz MC.CRR.tz MC.CFL.rx MC.CFR.rx MC.CRL.rx MC.CRR.rx MC.CFL.ry MC.CFR.ry MC.CRL.ry MC.CRR.ry MC.CFL.rz MC.CFR.rz MC.CRL.rz MC.CRR.rz MC.SpringFL.Frc MC.SpringFR.Frc MC.SpringRL.Frc MC.SpringRR.Frc MC.SpringFL.l MC.SpringFR.l MC.SpringRL.l MC.SpringRR.l MC.StabiFL.Frc MC.StabiFR.Frc MC.StabiRL.Frc MC.StabiRR.Frc MC.StabiFL.l MC.StabiFR.l MC.StabiRL.l MC.StabiRR.l MC.DampFL.Frc MC.DampFR.Frc MC.DampRL.Frc MC.DampRR.Frc MC.DampFL.v MC.DampFR.v MC.DampRL.v MC.DampRR.v MC.FxFL MC.FxFR MC.FxRL MC.FxRR MC.FyFL MC.FyFR MC.FyRL MC.FyRR MC.FzFL MC.FzFR MC.FzRL MC.FzRR MC.LongSlipFL MC.LongSlipFR MC.LongSlipRL MC.LongSlipRR MC.SlipAngleFL MC.SlipAngleFR MC.SlipAngleRL MC.SlipAngleRR MC.ToeFL MC.ToeFR MC.ToeRL MC.ToeRR MC.TrqAlignFL MC.TrqAlignFR MC.TrqAlignRL MC.TrqAlignRR Brake.pFL_FL Brake.pFR_FL Brake.pRL_FL Brake.pRR_FL Brake.Trq_FL_tot Brake.Trq_FR_tot Brake.Trq_RL_tot Brake.Trq_RR_tot PT.FL.rotv PT.FR.rotv PT.RL.rotv PT.RR.rotv PT.FL.Trq_Drive PT.FR.Trq_Drive PT.RL.Trq_Drive PT.RR.Trq_Drive PT.FL.Trq_B2W PT.FR.Trq_B2W PT.RL.Trq_B2W PT.RR.Trq_B2W
}
    QueryTimeout            {1000}
    RefQuant                {Time time T t WheelTravel.Left Implicit}
    SaveSettingsOnExit      {1}
    StartupDataWin          {1}
    WhiteDiagBackground     {0}
}
array set __graphs {
    APO.Debug               {auto	""	auto	auto}
    APO.DictMsgSize         {auto	""	auto	auto}
    APO.nQuantities         {auto	""	auto	auto}
    Brake.Hyd.Sys.ESP.Att_0.p {auto	bar	auto	auto}
    Brake.Hyd.Sys.ESP.Att_0.v {auto	m^3	auto	auto}
    Brake.Hyd.Sys.ESP.Att_1.p {auto	bar	auto	auto}
    Brake.Hyd.Sys.ESP.Att_1.v {auto	m^3	auto	auto}
    Brake.Hyd.Sys.ESP.Booster.F {auto	N	auto	auto}
    Brake.Hyd.Sys.ESP.Cyl_FL.p {White	bar	auto	auto}
    Brake.Hyd.Sys.ESP.Cyl_FL.v {White	m^3	auto	auto}
    Brake.Hyd.Sys.ESP.Cyl_FR.p {Red	bar	auto	auto}
    Brake.Hyd.Sys.ESP.Cyl_FR.v {Red	m^3	auto	auto}
    Brake.Hyd.Sys.ESP.Cyl_RL.p {Green1	bar	auto	auto}
    Brake.Hyd.Sys.ESP.Cyl_RL.v {Green1	m^3	auto	auto}
    Brake.Hyd.Sys.ESP.Cyl_RR.p {Blue	bar	auto	auto}
    Brake.Hyd.Sys.ESP.Cyl_RR.v {Blue	m^3	auto	auto}
    Brake.Hyd.Sys.ESP.IN_FL.dp {White	bar	auto	auto}
    Brake.Hyd.Sys.ESP.IN_FL.q {White	m^3/s	auto	auto}
    Brake.Hyd.Sys.ESP.IN_FR.dp {Red	bar	auto	auto}
    Brake.Hyd.Sys.ESP.IN_FR.q {Red	m^3/s	auto	auto}
    Brake.Hyd.Sys.ESP.IN_RL.dp {Green1	bar	auto	auto}
    Brake.Hyd.Sys.ESP.IN_RL.q {Green1	m^3/s	auto	auto}
    Brake.Hyd.Sys.ESP.IN_RR.dp {Blue	bar	auto	auto}
    Brake.Hyd.Sys.ESP.IN_RR.q {Blue	m^3/s	auto	auto}
    Brake.Hyd.Sys.ESP.In_FL.alpha {White	""	auto	auto}
    Brake.Hyd.Sys.ESP.In_FL.state {White	""	auto	auto}
    Brake.Hyd.Sys.ESP.In_FR.alpha {Red	""	auto	auto}
    Brake.Hyd.Sys.ESP.In_FR.state {Red	""	auto	auto}
    Brake.Hyd.Sys.ESP.In_RL.alpha {Green1	""	auto	auto}
    Brake.Hyd.Sys.ESP.In_RL.state {Green1	""	auto	auto}
    Brake.Hyd.Sys.ESP.In_RR.alpha {Blue	""	auto	auto}
    Brake.Hyd.Sys.ESP.In_RR.state {Blue	""	auto	auto}
    Brake.Hyd.Sys.ESP.LPA_0.p {auto	bar	auto	auto}
    Brake.Hyd.Sys.ESP.LPA_0.v {auto	m^3	auto	auto}
    Brake.Hyd.Sys.ESP.LPA_1.p {auto	bar	auto	auto}
    Brake.Hyd.Sys.ESP.LPA_1.v {auto	m^3	auto	auto}
    Brake.Hyd.Sys.ESP.OUT_FL.dp {White	bar	auto	auto}
    Brake.Hyd.Sys.ESP.OUT_FL.q {White	m^3/s	auto	auto}
    Brake.Hyd.Sys.ESP.OUT_FR.dp {Red	bar	auto	auto}
    Brake.Hyd.Sys.ESP.OUT_FR.q {Red	m^3/s	auto	auto}
    Brake.Hyd.Sys.ESP.OUT_RL.dp {Green1	bar	auto	auto}
    Brake.Hyd.Sys.ESP.OUT_RL.q {Green1	m^3/s	auto	auto}
    Brake.Hyd.Sys.ESP.OUT_RR.dp {Blue	bar	auto	auto}
    Brake.Hyd.Sys.ESP.OUT_RR.q {Blue	m^3/s	auto	auto}
    Brake.Hyd.Sys.ESP.Out_FL.alpha {White	""	auto	auto}
    Brake.Hyd.Sys.ESP.Out_FL.state {White	""	auto	auto}
    Brake.Hyd.Sys.ESP.Out_FR.alpha {Red	""	auto	auto}
    Brake.Hyd.Sys.ESP.Out_FR.state {Red	""	auto	auto}
    Brake.Hyd.Sys.ESP.Out_RL.alpha {Green1	""	auto	auto}
    Brake.Hyd.Sys.ESP.Out_RL.state {Green1	""	auto	auto}
    Brake.Hyd.Sys.ESP.Out_RR.alpha {Blue	""	auto	auto}
    Brake.Hyd.Sys.ESP.Out_RR.state {Blue	""	auto	auto}
    Brake.Hyd.Sys.ESP.PV_0.alpha {auto	""	auto	auto}
    Brake.Hyd.Sys.ESP.PV_0.dp {auto	bar	auto	auto}
    Brake.Hyd.Sys.ESP.PV_0.q {auto	m^3/s	auto	auto}
    Brake.Hyd.Sys.ESP.PV_0.state {auto	""	auto	auto}
    Brake.Hyd.Sys.ESP.PV_1.alpha {auto	""	auto	auto}
    Brake.Hyd.Sys.ESP.PV_1.dp {auto	bar	auto	auto}
    Brake.Hyd.Sys.ESP.PV_1.q {auto	m^3/s	auto	auto}
    Brake.Hyd.Sys.ESP.PV_1.state {auto	""	auto	auto}
    Brake.Hyd.Sys.ESP.Pu_0.dp {auto	bar	auto	auto}
    Brake.Hyd.Sys.ESP.Pu_0.q {auto	m^3/s	auto	auto}
    Brake.Hyd.Sys.ESP.Pu_1.dp {auto	bar	auto	auto}
    Brake.Hyd.Sys.ESP.Pu_1.q {auto	m^3/s	auto	auto}
    Brake.Hyd.Sys.ESP.Pump.dp {auto	bar	auto	auto}
    Brake.Hyd.Sys.ESP.SV_0.alpha {auto	""	auto	auto}
    Brake.Hyd.Sys.ESP.SV_0.dp {auto	bar	auto	auto}
    Brake.Hyd.Sys.ESP.SV_0.q {auto	m^3/s	auto	auto}
    Brake.Hyd.Sys.ESP.SV_0.state {auto	""	auto	auto}
    Brake.Hyd.Sys.ESP.SV_1.alpha {auto	""	auto	auto}
    Brake.Hyd.Sys.ESP.SV_1.dp {auto	bar	auto	auto}
    Brake.Hyd.Sys.ESP.SV_1.q {auto	m^3/s	auto	auto}
    Brake.Hyd.Sys.ESP.SV_1.state {auto	""	auto	auto}
    Brake.Hyd.Sys.ESP.SuppL_0.p {auto	bar	auto	auto}
    Brake.Hyd.Sys.ESP.SuppL_0.v {auto	m^3	auto	auto}
    Brake.Hyd.Sys.ESP.SuppL_1.p {auto	bar	auto	auto}
    Brake.Hyd.Sys.ESP.SuppL_1.v {auto	m^3	auto	auto}
    Brake.Hyd.Sys.ESP.nPump {auto	""	auto	auto}
    Brake.Park              {auto	""	auto	auto}
    Brake.Pedal             {auto	""	auto	auto}
    Car.Aero.Frc_1.x        {auto	N	auto	auto}
    Car.Aero.Frc_1.y        {auto	N	auto	auto}
    Car.Aero.Frc_1.z        {auto	N	auto	auto}
    Car.Aero.Trq_1.x        {auto	Nm	auto	auto}
    Car.Aero.Trq_1.y        {auto	Nm	auto	auto}
    Car.Aero.Trq_1.z        {auto	Nm	auto	auto}
    Car.Aero.tau2_1         {auto	deg	auto	auto}
    Car.Aero.tau_1          {auto	deg	auto	auto}
    Car.Aero.vres_1.x       {auto	km/h	0	120}
    Car.Aero.vres_1.y       {auto	km/h	0	120}
    Car.Aero.vres_1.z       {auto	km/h	0	120}
    Car.Con.alHori          {auto	m/s^2	-10	10}
    Car.Con.atHori          {auto	m/s^2	-10	10}
    Car.Con.ax              {auto	m/s^2	-10	10}
    Car.Con.ax_1            {auto	m/s^2	-10	10}
    Car.Con.ay              {auto	m/s^2	-10	10}
    Car.Con.ay_1            {auto	m/s^2	-10	10}
    Car.Con.az              {auto	m/s^2	-10	10}
    Car.Con.az_1            {auto	m/s^2	-10	10}
    Car.Con.tx              {auto	m	auto	auto}
    Car.Con.ty              {auto	m	auto	auto}
    Car.Con.tz              {auto	m	auto	auto}
    Car.Con.v               {auto	km/h	0	120}
    Car.Con.vHori           {auto	km/h	0	120}
    Car.Con.vx_1            {auto	km/h	0	120}
    Car.Con.vy_1            {auto	km/h	0	120}
    Car.Con.vz_1            {auto	km/h	0	120}
    Car.ConA.Pitch_X        {auto	deg	auto	auto}
    Car.ConA.Roll_X         {auto	deg	auto	auto}
    Car.Distance            {auto	m	auto	auto}
    Car.Fr1.ax              {auto	m/s^2	-10	10}
    Car.Fr1.ay              {auto	m/s^2	-10	10}
    Car.Fr1.az              {auto	m/s^2	-10	10}
    Car.Fr1.rx              {auto	deg	auto	auto}
    Car.Fr1.ry              {auto	deg	auto	auto}
    Car.Fr1.rz              {auto	deg	auto	auto}
    Car.Fr1.tx              {auto	m	auto	auto}
    Car.Fr1.ty              {auto	m	auto	auto}
    Car.Fr1.tz              {auto	m	auto	auto}
    Car.Fr1.vx              {auto	km/h	0	120}
    Car.Fr1.vy              {auto	km/h	0	120}
    Car.Fr1.vz              {auto	km/h	0	120}
    Car.Gen.ax              {auto	m/s^2	-10	10}
    Car.Gen.ax_1            {auto	m/s^2	-10	10}
    Car.Gen.ay              {auto	m/s^2	-10	10}
    Car.Gen.ay_1            {auto	m/s^2	-10	10}
    Car.Gen.az              {auto	m/s^2	-10	10}
    Car.Gen.az_1            {auto	m/s^2	-10	10}
    Car.Gen.tx              {auto	m	auto	auto}
    Car.Gen.ty              {auto	m	auto	auto}
    Car.Gen.tz              {auto	m	auto	auto}
    Car.Gen.vx_1            {auto	km/h	0	120}
    Car.Gen.vy_1            {auto	km/h	0	120}
    Car.Gen.vz_1            {auto	km/h	0	120}
    Car.Hitch.Frc2Car.x     {auto	N	auto	auto}
    Car.Hitch.Frc2Car.y     {auto	N	auto	auto}
    Car.Hitch.Frc2Car.z     {auto	N	auto	auto}
    Car.Hitch.Trq2Car.x     {auto	Nm	auto	auto}
    Car.Hitch.Trq2Car.y     {auto	Nm	auto	auto}
    Car.Hitch.Trq2Car.z     {auto	Nm	auto	auto}
    Car.Hitch.tx            {auto	m	auto	auto}
    Car.Hitch.ty            {auto	m	auto	auto}
    Car.Hitch.tz            {auto	m	auto	auto}
    Car.Hitch.vx            {auto	km/h	0	120}
    Car.Hitch.vy            {auto	km/h	0	120}
    Car.Hitch.vz            {auto	km/h	0	120}
    Car.Jack.FzFL           {auto	N	auto	auto}
    Car.Jack.FzFR           {auto	N	auto	auto}
    Car.Jack.FzRL           {auto	N	auto	auto}
    Car.Jack.FzRR           {auto	N	auto	auto}
    Car.Jack.tzFL           {auto	m	auto	auto}
    Car.Jack.tzFR           {auto	m	auto	auto}
    Car.Jack.tzRL           {auto	m	auto	auto}
    Car.Jack.tzRR           {auto	m	auto	auto}
    Car.KinPitchCenter_L.x  {auto	m	auto	auto}
    Car.KinPitchCenter_L.x_1 {auto	m	auto	auto}
    Car.KinPitchCenter_L.y_1 {auto	m	auto	auto}
    Car.KinPitchCenter_L.z  {auto	m	auto	auto}
    Car.KinPitchCenter_L.z_1 {auto	m	auto	auto}
    Car.KinPitchCenter_R.x  {auto	m	auto	auto}
    Car.KinPitchCenter_R.x_1 {auto	m	auto	auto}
    Car.KinPitchCenter_R.y_1 {auto	m	auto	auto}
    Car.KinPitchCenter_R.z  {auto	m	auto	auto}
    Car.KinPitchCenter_R.z_1 {auto	m	auto	auto}
    Car.Load.0.mass         {auto	kg	auto	auto}
    Car.Load.0.tx           {auto	m	auto	auto}
    Car.Load.0.ty           {auto	m	auto	auto}
    Car.Load.0.tz           {auto	m	auto	auto}
    Car.Load.1.mass         {auto	kg	auto	auto}
    Car.Load.1.tx           {auto	m	auto	auto}
    Car.Load.1.ty           {auto	m	auto	auto}
    Car.Load.1.tz           {auto	m	auto	auto}
    Car.Load.2.mass         {auto	kg	auto	auto}
    Car.Load.2.tx           {auto	m	auto	auto}
    Car.Load.2.ty           {auto	m	auto	auto}
    Car.Load.2.tz           {auto	m	auto	auto}
    Car.Load.3.mass         {auto	kg	auto	auto}
    Car.Load.3.tx           {auto	m	auto	auto}
    Car.Load.3.ty           {auto	m	auto	auto}
    Car.Load.3.tz           {auto	m	auto	auto}
    Car.Pitch               {auto	deg	auto	auto}
    Car.PitchAcc            {auto	deg/s^2	auto	auto}
    Car.PitchVel            {auto	deg/s	auto	auto}
    Car.Road.GCS.Elev       {auto	m	auto	auto}
    Car.Road.GCS.Lat        {auto	deg	auto	auto}
    Car.Road.GCS.Long       {auto	deg	auto	auto}
    Car.Road.Lane.Act.LaneId {auto	""	auto	auto}
    Car.Road.Lane.Act.Type  {auto	""	auto	auto}
    Car.Road.Lane.Act.Width {auto	m	auto	auto}
    Car.Road.Lane.Act.isRight {auto	""	auto	auto}
    Car.Road.Lane.Act.tMidLane {auto	m	auto	auto}
    Car.Road.Lane.OnLeft.LaneId {auto	""	auto	auto}
    Car.Road.Lane.OnLeft.Type {auto	""	auto	auto}
    Car.Road.Lane.OnLeft.Width {auto	m	auto	auto}
    Car.Road.Lane.OnLeft.isRight {auto	""	auto	auto}
    Car.Road.Lane.OnLeft.tMidLane {auto	m	auto	auto}
    Car.Road.Lane.OnRight.LaneId {auto	""	auto	auto}
    Car.Road.Lane.OnRight.Type {auto	""	auto	auto}
    Car.Road.Lane.OnRight.Width {auto	m	auto	auto}
    Car.Road.Lane.OnRight.isRight {auto	""	auto	auto}
    Car.Road.Lane.OnRight.tMidLane {auto	m	auto	auto}
    Car.Road.Lane.nLeft     {auto	""	auto	auto}
    Car.Road.Lane.nRight    {auto	""	auto	auto}
    Car.Road.Path.DevAng    {auto	deg	auto	auto}
    Car.Road.Path.DevDist   {auto	m	auto	auto}
    Car.Road.Path.LatSlope  {auto	deg	auto	auto}
    Car.Road.Path.LongSlope {auto	deg	auto	auto}
    Car.Road.Route.DevAng   {auto	deg	auto	auto}
    Car.Road.Route.DevDist  {auto	m	auto	auto}
    Car.Road.Route.LatSlope {auto	deg	auto	auto}
    Car.Road.Route.LongSlope {auto	deg	auto	auto}
    Car.Road.sRoad          {Blue m -1.0 1.0}
    Car.Road.tx             {auto	m	auto	auto}
    Car.Road.ty             {auto	m	auto	auto}
    Car.Road.tz             {auto	m	auto	auto}
    Car.Roll                {auto	deg	auto	auto}
    Car.RollAcc             {auto	deg/s^2	auto	auto}
    Car.RollKin_F           {auto	deg	auto	auto}
    Car.RollKin_R           {auto	deg	auto	auto}
    Car.RollVel             {auto	deg/s	auto	auto}
    Car.SideSlipAngle       {auto	deg	auto	auto}
    Car.SideSlipAngle2      {auto	deg	auto	auto}
    Car.SideSlipAngleVel    {auto	deg/s	auto	auto}
    Car.SimPhase            {auto	""	auto	auto}
    Car.SlotCar.Deviation   {auto	m	auto	auto}
    Car.SlotCar.State       {auto	""	auto	auto}
    Car.StandbyMode         {auto	""	auto	auto}
    Car.TrackCurv           {auto	1/m	auto	auto}
    Car.TrackRadius         {auto	m	auto	auto}
    Car.Virtual.Frc_0.x     {auto	N	auto	auto}
    Car.Virtual.Frc_0.y     {auto	N	auto	auto}
    Car.Virtual.Frc_0.z     {auto	N	auto	auto}
    Car.Virtual.Frc_1.x     {auto	N	auto	auto}
    Car.Virtual.Frc_1.y     {auto	N	auto	auto}
    Car.Virtual.Frc_1.z     {auto	N	auto	auto}
    Car.Virtual.Trq_0.x     {auto	Nm	auto	auto}
    Car.Virtual.Trq_0.y     {auto	Nm	auto	auto}
    Car.Virtual.Trq_0.z     {auto	Nm	auto	auto}
    Car.Virtual.Trq_1.x     {auto	Nm	auto	auto}
    Car.Virtual.Trq_1.y     {auto	Nm	auto	auto}
    Car.Virtual.Trq_1.z     {auto	Nm	auto	auto}
    Car.Yaw                 {auto	deg	auto	auto}
    Car.YawAcc              {auto	deg/s^2	auto	auto}
    Car.YawRate             {auto	deg/s	auto	auto}
    Car.YawVel              {auto	deg/s	auto	auto}
    Car.alHori              {auto	m/s^2	-10	10}
    Car.atHori              {auto	m/s^2	-10	10}
    Car.ax                  {auto	m/s^2	-10	10}
    Car.ay                  {auto	m/s^2	-10	10}
    Car.az                  {auto	m/s^2	-10	10}
    Car.tx                  {auto	m	auto	auto}
    Car.ty                  {auto	m	auto	auto}
    Car.tz                  {auto	m	auto	auto}
    Car.v                   {auto	km/h	0	120}
    Car.vx                  {auto	km/h	0	120}
    Car.vy                  {auto	km/h	0	120}
    Car.vz                  {auto	km/h	0	120}
    DM.Brake                {auto	""	0	1.2}
    DM.BrakePark            {auto	""	0	1.2}
    DM.Clutch               {auto	""	0	1.2}
    DM.Gas                  {auto	""	0	1.2}
    DM.GearNo               {auto	""	0	1.2}
    DM.GearNo.Trgt          {auto	""	0	1.2}
    DM.Handbrake            {auto	""	0	1.2}
    DM.Key                  {auto	""	0	1.2}
    DM.LaneOffset           {auto	m	auto	auto}
    DM.Lap.No               {auto	""	0	1.2}
    DM.Lap.Time             {auto	s	auto	auto}
    DM.Lights.FogFront      {auto	""	0	1.2}
    DM.Lights.FogRear       {auto	""	0	1.2}
    DM.Lights.Hazard        {auto	""	0	1.2}
    DM.Lights.HighBeam      {auto	""	0	1.2}
    DM.Lights.Indicator     {auto	""	0	1.2}
    DM.Lights.MainLight     {auto	""	0	1.2}
    DM.ManDist              {auto	m	auto	auto}
    DM.ManNo                {auto	""	0	1.2}
    DM.ManTime              {auto	s	auto	auto}
    DM.OperationState_trg   {auto	""	0	1.2}
    DM.OperatorActive       {auto	""	0	1.2}
    DM.SST                  {auto	""	0	1.2}
    DM.SelectorCtrl         {auto	""	0	1.2}
    DM.Shifting             {auto	""	0	1.2}
    DM.SpeedLimit           {auto	m/s	auto	auto}
    DM.SpeedOffset          {auto	m/s	auto	auto}
    DM.Steer.Ang            {auto	deg	auto	auto}
    DM.Steer.AngAcc         {auto	deg/s^2	auto	auto}
    DM.Steer.AngVel         {auto	deg/s	auto	auto}
    DM.Steer.SinusFreq      {auto	Hz	auto	auto}
    DM.Steer.Trq            {auto	Nm	auto	auto}
    DM.SteerBy              {auto	""	0	1.2}
    DM.StopDist             {auto	m	auto	auto}
    DM.StopTime             {auto	s	auto	auto}
    DM.TriggerPoint.Dist    {auto	m	auto	auto}
    DM.TriggerPoint.Id      {auto	""	0	1.2}
    DM.TriggerPoint.Time    {auto	s	auto	auto}
    DM.UserSignal_0         {auto	""	0	1.2}
    DM.UserSignal_1         {auto	""	0	1.2}
    DM.UserSignal_2         {auto	""	0	1.2}
    DM.UserSignal_3         {auto	""	0	1.2}
    DM.UserSignal_4         {auto	""	0	1.2}
    DM.ax.Trgt              {auto	m/s^2	auto	auto}
    DM.v.Trgt               {auto	km/h	0	120}
    DM.v.Trgt_LimitHi       {auto	km/h	0	120}
    DM.v.Trgt_LimitLo       {auto	km/h	0	120}
    DM.vdelta.Trgt          {auto	km/h	0	120}
    DeltaT                  {auto	s	auto	auto}
    DeltaTPeak              {auto	s	auto	auto}
    Driver.Adapt.Phase      {auto	""	auto	auto}
    Driver.Brake            {auto	""	auto	auto}
    Driver.BrakeLever       {auto	""	auto	auto}
    Driver.BrakeLever_UDrvIn {auto	""	auto	auto}
    Driver.BrakePark        {auto	""	auto	auto}
    Driver.BrakePark_UDrvIn {auto	""	auto	auto}
    Driver.Brake_UDrvIn     {auto	""	auto	auto}
    Driver.Clutch           {auto	""	auto	auto}
    Driver.Clutch_UDrvIn    {auto	""	auto	auto}
    Driver.Gas              {auto	""	auto	auto}
    Driver.Gas_UDrvIn       {auto	""	auto	auto}
    Driver.GearNo           {auto	""	auto	auto}
    Driver.GearNoTrgt       {auto	""	auto	auto}
    Driver.GearNo_UDrvIn    {auto	""	auto	auto}
    Driver.Lat.dy           {auto	m	auto	auto}
    Driver.Lat.passive      {auto	""	auto	auto}
    Driver.Long.dv          {auto	m/s	auto	auto}
    Driver.Long.passive     {auto	""	auto	auto}
    Driver.ReCon.ADAS_LD_Coef {auto	""	auto	auto}
    Driver.ReCon.ADAS_LD_T  {auto	""	auto	auto}
    Driver.ReCon.Accel      {auto	m/s^2	auto	auto}
    Driver.ReCon.Decel      {auto	m/s^2	auto	auto}
    Driver.ReCon.DriveChar.CF_GGExp {auto	""	auto	auto}
    Driver.ReCon.DriveChar.CF_axy {auto	""	auto	auto}
    Driver.ReCon.DriveChar.iChange {auto	""	auto	auto}
    Driver.ReCon.DriveMode  {auto	""	auto	auto}
    Driver.ReCon.JunDir     {auto	""	auto	auto}
    Driver.ReCon.Speed      {auto	km/h	auto	auto}
    Driver.ReCon.StopDist   {auto	m	auto	auto}
    Driver.ReCon.StopTask   {auto	""	auto	auto}
    Driver.ReCon.StopTime   {auto	s	auto	auto}
    Driver.ReCon.Task       {auto	""	auto	auto}
    Driver.ReCon.Task_lat   {auto	""	auto	auto}
    Driver.ReCon.Trf_Consider {auto	""	auto	auto}
    Driver.ReCon.Trf_FOL.Id {auto	""	auto	auto}
    Driver.ReCon.Trf_FOL.Targ_Dtct {auto	""	auto	auto}
    Driver.ReCon.Trf_FOL.dDist {auto	m	auto	auto}
    Driver.ReCon.Trf_FOL.dSpeed {auto	m/s	auto	auto}
    Driver.ReCon.Trf_ONC.Id {auto	""	auto	auto}
    Driver.ReCon.Trf_ONC.Targ_Dtct {auto	""	auto	auto}
    Driver.ReCon.Trf_ONC.dDist {auto	m	auto	auto}
    Driver.ReCon.Trf_ONC.dSpeed {auto	m/s	auto	auto}
    Driver.ReCon.Trf_OTR.Id {auto	""	auto	auto}
    Driver.ReCon.Trf_OTR.Targ_Dtct {auto	""	auto	auto}
    Driver.ReCon.Trf_OTR.dDist {auto	m	auto	auto}
    Driver.ReCon.Trf_OTR.dSpeed {auto	m/s	auto	auto}
    Driver.ReCon.Trf_Overtake {auto	""	auto	auto}
    Driver.SelectorCtrl     {auto	""	auto	auto}
    Driver.SetGearNo        {auto	""	auto	auto}
    Driver.Shifting         {auto	""	auto	auto}
    Driver.Steer.Ang        {auto	deg	auto	auto}
    Driver.Steer.AngAcc     {auto	deg/s^2	auto	auto}
    Driver.Steer.AngVel     {auto	deg/s	auto	auto}
    Driver.Steer.Trq        {auto	Nm	auto	auto}
    Driver.UDrv.Active      {auto	""	auto	auto}
    Driver.WaitFlag         {auto	""	auto	auto}
    Env.AirDensity          {auto	kg/m^3	auto	auto}
    Env.AirHumidity         {auto	""	auto	auto}
    Env.AirPressure         {auto	bar	auto	auto}
    Env.SolarRadiation      {auto	W/m^2	auto	auto}
    Env.Temperature         {auto	K	auto	auto}
    Env.Time                {auto	hours	auto	auto}
    Env.WindVel_ext.x       {auto	m/s	auto	auto}
    Env.WindVel_ext.y       {auto	m/s	auto	auto}
    Env.WindVel_ext.z       {auto	m/s	auto	auto}
    Env.WindVel_tot.x       {auto	m/s	auto	auto}
    Env.WindVel_tot.y       {auto	m/s	auto	auto}
    Env.WindVel_tot.z       {auto	m/s	auto	auto}
    Env.YearDay             {auto	days	auto	auto}
    Log.nError              {auto	""	auto	auto}
    Log.nLog                {auto	""	auto	auto}
    Log.nWarn               {auto	""	auto	auto}
    PT.Control.Ignition     {auto	""	auto	auto}
    PT.Control.OperationError {auto	""	auto	auto}
    PT.Control.OperationState {auto	""	auto	auto}
    PT.DL.iDiff_mean        {auto	""	auto	auto}
    PT.Engine.rotv          {auto	rpm	0	7000}
    PT.GearBox.GearNo       {auto	""	auto	auto}
    PT.Trq_Supp2Bdy1.y      {auto	Nm	auto	auto}
    PT.Trq_Supp2Bdy1B.y     {auto	Nm	auto	auto}
    PT.Trq_Supp2BdyEng.x    {auto	Nm	auto	auto}
    PT.Trq_Supp2BdyEng.y    {auto	Nm	auto	auto}
    SC.MemFree              {auto	Byte	auto	auto}
    SC.MemUsed              {auto	Byte	auto	auto}
    SC.MemUsed.TRNo         {auto	""	auto	auto}
    SC.Start.No             {auto	""	auto	auto}
    SC.State                {auto	""	auto	auto}
    SC.TAccel               {auto	""	auto	auto}
    Steer.AssistFrc         {auto	N	auto	auto}
    Steer.AssistFrc_Ext     {auto	N	auto	auto}
    Steer.AssistTrqCol      {auto	Nm	auto	auto}
    Steer.AssistTrqCol_Ext  {auto	Nm	auto	auto}
    Steer.AssistTrqPin      {auto	Nm	auto	auto}
    Steer.AssistTrqPin_Ext  {auto	Nm	auto	auto}
    Steer.Cfg.PosSign       {auto	""	auto	auto}
    Steer.L.Frc             {auto	N	auto	auto}
    Steer.L.Inert           {auto	kg	auto	auto}
    Steer.L.iSteer2q        {auto	m/deg	auto	auto}
    Steer.L.q               {auto	m	auto	auto}
    Steer.L.qp              {auto	m/s	auto	auto}
    Steer.L.qpp             {auto	m/s^2	auto	auto}
    Steer.R.Frc             {auto	N	auto	auto}
    Steer.R.Inert           {auto	kg	auto	auto}
    Steer.R.iSteer2q        {auto	m/deg	auto	auto}
    Steer.R.q               {auto	m	auto	auto}
    Steer.R.qp              {auto	m/s	auto	auto}
    Steer.R.qpp             {auto	m/s^2	auto	auto}
    Steer.SteerBy           {auto	""	auto	auto}
    Steer.WhlAcc            {auto	deg/s^2	auto	auto}
    Steer.WhlAng            {auto	deg	auto	auto}
    Steer.WhlTrq            {auto	Nm	auto	auto}
    Steer.WhlTrqStatic      {auto	Nm	auto	auto}
    Steer.WhlVel            {auto	deg/s	auto	auto}
    TCPU.AposEvalSend       {auto	ms	0	1.2}
    TCPU.AposPoll           {auto	ms	0	1.2}
    TCPU.Brake              {auto	ms	0	1.2}
    TCPU.Cycle              {auto	ms	0	1.2}
    TCPU.DrivMan            {auto	ms	0	1.2}
    TCPU.In                 {auto	ms	0	1.2}
    TCPU.Out                {auto	ms	0	1.2}
    TCPU.PowerTrain         {auto	ms	0	1.2}
    TCPU.Sensors            {auto	ms	0	1.2}
    TCPU.Total              {auto	ms	0	1.2}
    TCPU.Traffic            {auto	ms	0	1.2}
    TCPU.Trailer            {auto	ms	0	1.2}
    TCPU.User               {auto	ms	0	1.2}
    TCPU.Vehicle            {auto	ms	0	1.2}
    TCPU.VehicleControl     {auto	ms	0	1.2}
    Time                    {auto	s	auto	auto}
    Time.Global             {auto	s	auto	auto}
    Time.WC                 {auto	s	auto	auto}
    Traffic.Cross.Distance  {Cyan m -1.0 1.0}
    Traffic.Cross.sRoad     {Cyan m -1.0 1.0}
    Traffic.Cross2.sRoad    {Gray m -1.0 1.0}
    UserOut_00              {auto	""	auto	auto}
    UserOut_01              {auto	""	auto	auto}
    UserOut_02              {auto	""	auto	auto}
    UserOut_03              {auto	""	auto	auto}
    UserOut_04              {auto	""	auto	auto}
    UserOut_05              {auto	""	auto	auto}
    UserOut_06              {auto	""	auto	auto}
    UserOut_07              {auto	""	auto	auto}
    UserOut_08              {auto	""	auto	auto}
    UserOut_09              {auto	""	auto	auto}
    VC.Brake                {auto	""	auto	auto}
    VC.BrakePark            {auto	""	auto	auto}
    VC.Clutch               {auto	""	auto	auto}
    VC.Gas                  {auto	""	auto	auto}
    VC.GearNo               {auto	""	auto	auto}
    VC.Key                  {auto	""	auto	auto}
    VC.Lights.Brake         {auto	""	auto	auto}
    VC.Lights.Daytime       {auto	""	auto	auto}
    VC.Lights.FogFrontL     {auto	""	auto	auto}
    VC.Lights.FogFrontR     {auto	""	auto	auto}
    VC.Lights.FogRear       {auto	""	auto	auto}
    VC.Lights.HighBeam      {auto	""	auto	auto}
    VC.Lights.IndL          {auto	""	auto	auto}
    VC.Lights.IndR          {auto	""	auto	auto}
    VC.Lights.LowBeam       {auto	""	auto	auto}
    VC.Lights.ParkL         {auto	""	auto	auto}
    VC.Lights.ParkR         {auto	""	auto	auto}
    VC.Lights.Reverse       {auto	""	auto	auto}
    VC.Lights.bm            {auto	""	auto	auto}
    VC.SST                  {auto	""	auto	auto}
    VC.SelectorCtrl         {auto	""	auto	auto}
    VC.Steer.Ang            {auto	deg	auto	auto}
    VC.Steer.AngAcc         {auto	deg/s^2	auto	auto}
    VC.Steer.AngVel         {auto	deg/s	auto	auto}
    VC.Steer.Trq            {auto	Nm	auto	auto}
    VC.UserSignal_0         {auto	""	auto	auto}
    VC.UserSignal_1         {auto	""	auto	auto}
    VC.UserSignal_2         {auto	""	auto	auto}
    VC.UserSignal_3         {auto	""	auto	auto}
    VC.UserSignal_4         {auto	""	auto	auto}
    Vhcl.Distance           {auto	m	auto	auto}
    Vhcl.Engine.rotv        {auto	deg/s	auto	auto}
    Vhcl.FL.Fx              {White	N	auto	auto}
    Vhcl.FL.Fy              {White	N	auto	auto}
    Vhcl.FL.Fz              {White	N	auto	auto}
    Vhcl.FL.LongSlip        {White	""	auto	auto}
    Vhcl.FL.SideSlip        {White	deg	auto	auto}
    Vhcl.FL.Trq_B2WC        {White	Nm	auto	auto}
    Vhcl.FL.Trq_Brake       {White	Nm	auto	auto}
    Vhcl.FL.Trq_DL2WC       {White	Nm	auto	auto}
    Vhcl.FL.Trq_T2W         {White	Nm	auto	auto}
    Vhcl.FL.Trq_WhlBearing  {White	Nm	auto	auto}
    Vhcl.FL.rot             {White	deg	auto	auto}
    Vhcl.FL.rotv            {White	deg/s	auto	auto}
    Vhcl.FL.rx              {White	deg	auto	auto}
    Vhcl.FL.ry              {White	deg	auto	auto}
    Vhcl.FL.rz              {White	deg	auto	auto}
    Vhcl.FL.tx              {White	m	auto	auto}
    Vhcl.FL.ty              {White	m	auto	auto}
    Vhcl.FL.tz              {White	m	auto	auto}
    Vhcl.FL.vBelt           {White	km/h	0	120}
    Vhcl.FR.Fx              {Red	N	auto	auto}
    Vhcl.FR.Fy              {Red	N	auto	auto}
    Vhcl.FR.Fz              {Red	N	auto	auto}
    Vhcl.FR.LongSlip        {Red	""	auto	auto}
    Vhcl.FR.SideSlip        {Red	deg	auto	auto}
    Vhcl.FR.Trq_B2WC        {Red	Nm	auto	auto}
    Vhcl.FR.Trq_Brake       {Red	Nm	auto	auto}
    Vhcl.FR.Trq_DL2WC       {Red	Nm	auto	auto}
    Vhcl.FR.Trq_T2W         {Red	Nm	auto	auto}
    Vhcl.FR.Trq_WhlBearing  {Red	Nm	auto	auto}
    Vhcl.FR.rot             {Red	deg	auto	auto}
    Vhcl.FR.rotv            {Red	deg/s	auto	auto}
    Vhcl.FR.rx              {Red	deg	auto	auto}
    Vhcl.FR.ry              {Red	deg	auto	auto}
    Vhcl.FR.rz              {Red	deg	auto	auto}
    Vhcl.FR.tx              {Red	m	auto	auto}
    Vhcl.FR.ty              {Red	m	auto	auto}
    Vhcl.FR.tz              {Red	m	auto	auto}
    Vhcl.FR.vBelt           {Red	km/h	0	120}
    Vhcl.Fr1.x              {auto	m	auto	auto}
    Vhcl.Fr1.y              {auto	m	auto	auto}
    Vhcl.Fr1.z              {auto	m	auto	auto}
    Vhcl.Fr1B.rx            {auto	deg	auto	auto}
    Vhcl.Fr1B.ry            {auto	deg	auto	auto}
    Vhcl.GearNo             {auto	""	auto	auto}
    Vhcl.Hitch.x            {auto	m	auto	auto}
    Vhcl.Hitch.y            {auto	m	auto	auto}
    Vhcl.Hitch.z            {auto	m	auto	auto}
    Vhcl.Ignition           {auto	""	auto	auto}
    Vhcl.OperationError     {auto	""	auto	auto}
    Vhcl.OperationState     {auto	""	auto	auto}
    Vhcl.Pitch              {auto	deg	auto	auto}
    Vhcl.PitchAcc           {auto	deg/s^2	auto	auto}
    Vhcl.PitchVel           {auto	deg/s	auto	auto}
    Vhcl.PoI.GCS.Elev       {auto	m	auto	auto}
    Vhcl.PoI.GCS.Lat        {auto	deg	auto	auto}
    Vhcl.PoI.GCS.Long       {auto	deg	auto	auto}
    Vhcl.PoI.ax             {auto	m/s^2	auto	auto}
    Vhcl.PoI.ax_1           {auto	m/s^2	auto	auto}
    Vhcl.PoI.ay             {auto	m/s^2	auto	auto}
    Vhcl.PoI.ay_1           {auto	m/s^2	auto	auto}
    Vhcl.PoI.az             {auto	m/s^2	auto	auto}
    Vhcl.PoI.az_1           {auto	m/s^2	auto	auto}
    Vhcl.PoI.vx             {auto	km/h	0	120}
    Vhcl.PoI.vx_1           {auto	km/h	0	120}
    Vhcl.PoI.vy             {auto	km/h	0	120}
    Vhcl.PoI.vy_1           {auto	km/h	0	120}
    Vhcl.PoI.vz             {auto	km/h	0	120}
    Vhcl.PoI.vz_1           {auto	km/h	0	120}
    Vhcl.PoI.x              {auto	m	auto	auto}
    Vhcl.PoI.y              {auto	m	auto	auto}
    Vhcl.PoI.z              {auto	m	auto	auto}
    Vhcl.RL.Fx              {Green1	N	auto	auto}
    Vhcl.RL.FxTwin          {Green1	N	auto	auto}
    Vhcl.RL.Fy              {Green1	N	auto	auto}
    Vhcl.RL.FyTwin          {Green1	N	auto	auto}
    Vhcl.RL.Fz              {Green1	N	auto	auto}
    Vhcl.RL.FzTwin          {Green1	N	auto	auto}
    Vhcl.RL.LongSlip        {Green1	""	auto	auto}
    Vhcl.RL.SideSlip        {Green1	deg	auto	auto}
    Vhcl.RL.Trq_B2WC        {Green1	Nm	auto	auto}
    Vhcl.RL.Trq_Brake       {Green1	Nm	auto	auto}
    Vhcl.RL.Trq_DL2WC       {Green1	Nm	auto	auto}
    Vhcl.RL.Trq_T2W         {Green1	Nm	auto	auto}
    Vhcl.RL.Trq_WhlBearing  {Green1	Nm	auto	auto}
    Vhcl.RL.rot             {Green1	deg	auto	auto}
    Vhcl.RL.rotv            {Green1	deg/s	auto	auto}
    Vhcl.RL.rx              {Green1	deg	auto	auto}
    Vhcl.RL.ry              {Green1	deg	auto	auto}
    Vhcl.RL.rz              {Green1	deg	auto	auto}
    Vhcl.RL.tx              {Green1	m	auto	auto}
    Vhcl.RL.ty              {Green1	m	auto	auto}
    Vhcl.RL.tz              {Green1	m	auto	auto}
    Vhcl.RL.vBelt           {Green1	km/h	0	120}
    Vhcl.RR.Fx              {Blue	N	auto	auto}
    Vhcl.RR.FxTwin          {Blue	N	auto	auto}
    Vhcl.RR.Fy              {Blue	N	auto	auto}
    Vhcl.RR.FyTwin          {Blue	N	auto	auto}
    Vhcl.RR.Fz              {Blue	N	auto	auto}
    Vhcl.RR.FzTwin          {Blue	N	auto	auto}
    Vhcl.RR.LongSlip        {Blue	""	auto	auto}
    Vhcl.RR.SideSlip        {Blue	deg	auto	auto}
    Vhcl.RR.Trq_B2WC        {Blue	Nm	auto	auto}
    Vhcl.RR.Trq_Brake       {Blue	Nm	auto	auto}
    Vhcl.RR.Trq_DL2WC       {Blue	Nm	auto	auto}
    Vhcl.RR.Trq_T2W         {Blue	Nm	auto	auto}
    Vhcl.RR.Trq_WhlBearing  {Blue	Nm	auto	auto}
    Vhcl.RR.rot             {Blue	deg	auto	auto}
    Vhcl.RR.rotv            {Blue	deg/s	auto	auto}
    Vhcl.RR.rx              {Blue	deg	auto	auto}
    Vhcl.RR.ry              {Blue	deg	auto	auto}
    Vhcl.RR.rz              {Blue	deg	auto	auto}
    Vhcl.RR.tx              {Blue	m	auto	auto}
    Vhcl.RR.ty              {Blue	m	auto	auto}
    Vhcl.RR.tz              {Blue	m	auto	auto}
    Vhcl.RR.vBelt           {Blue	km/h	0	120}
    Vhcl.Roll               {auto	deg	auto	auto}
    Vhcl.RollAcc            {auto	deg/s^2	auto	auto}
    Vhcl.RollVel            {auto	deg/s	auto	auto}
    Vhcl.Steer.Acc          {auto	deg/s^2	auto	auto}
    Vhcl.Steer.Ang          {auto	deg	auto	auto}
    Vhcl.Steer.Trq          {auto	Nm	auto	auto}
    Vhcl.Steer.Vel          {auto	deg/s	auto	auto}
    Vhcl.Wind.vx            {auto	km/h	0	120}
    Vhcl.Wind.vy            {auto	km/h	0	120}
    Vhcl.Wind.vz            {auto	km/h	0	120}
    Vhcl.Yaw                {auto	deg	auto	auto}
    Vhcl.YawAcc             {auto	deg/s^2	auto	auto}
    Vhcl.YawRate            {auto	deg/s	auto	auto}
    Vhcl.sRoad              {auto	m	auto	auto}
    Vhcl.sRoadAero          {auto	m	auto	auto}
    Vhcl.tRoad              {auto	m	auto	auto}
    Vhcl.v                  {auto	km/h	0	120}
    default                 { colorname unit min max }
}
array set __groups {
}
array set __diagconfs {
}
